version: "3"
  
services:
  postgres:
    image: postgres:15.5
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $POSTGRES_USER
      interval: 1s
      timeout: 10s  
        
  migrate:
    image: migrate/migrate:v4.17.0
    command:
     - -database
     - postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?sslmode=disable
     - -path
     - /migrations
     - up 
    volumes:
      - ../../migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
