version: "3"
  
x-postgres-creds: &postgres-creds
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD

services:
  update-watcher:
    image: tcaty/update-watcher
    command: 
      - "--config=/config.yaml"
    environment:
      <<: *postgres-creds
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      WEBHOOKS_DISCORD_URL: $WEBHOOKS_DISCORD_URL
    volumes:
      - ./config.yaml:/config.yaml
    depends_on:
      migrate:
        condition: service_completed_successfully

  postgres:
    image: postgres:15.5
    environment:
      <<: *postgres-creds
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $POSTGRES_USER
      interval: 5s
      timeout: 10s  
        
  migrate:
    image: migrate/migrate:v4.17.0
    command:
     - -database
     - postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?sslmode=disable
     - -path
     - /migrations
     - up 
    volumes:
      - ../../migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
