version: "3"
  
x-default-environment: &default-environment
  POSTGRES_DB: "update-watcher"
  POSTGRES_USER: "update-watcher"
  POSTGRES_PASSWORD: "changeme"

services:
  update-watcher:
    image: tcaty/update-watcher
    command: [ "--config=/config.yaml" ]
    environment:
      <<: *default-environment
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      WEBHOOKS_DISCORD_URL: "<url>"
    volumes:
      - ../config/examples/docker.yaml:/config.yaml

  postgres:
    image: postgres:15.5
    environment:
      <<: *default-environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
volumes:
  postgres-data:
