version: "3"
  
x-postgres-creds: &postgres-creds
  POSTGRES_DB: "update-watcher"
  POSTGRES_USER: "update-watcher"
  POSTGRES_PASSWORD: "changeme"
    
x-postgres-url: &postgres-url
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: 5432

services:
  update-watcher:
    image: tcaty/update-watcher
    command: 
      - "--config=/config.yaml"
    environment:
      <<:
        - *postgres-creds
        - *postgres-url
      # specify your secret discord webhook url here
      WEBHOOKS_DISCORD_URL: "<url>"
    volumes:
      - ../config/examples/docker.yaml:/config.yaml
    depends_on:
      - migrate

  postgres:
    image: postgres:15.5
    environment:
      <<: *postgres-creds
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
  migrate:
    image: migrate/migrate:v4.17.0
    entrypoint: 
      - "/entrypoint.sh"
    environment:
      <<:
        - *postgres-creds
        - *postgres-url
    volumes:
      - ../migrations:/migrations
      - ./scripts/entrypoint.sh:/entrypoint.sh
    depends_on:
      - postgres

volumes:
  postgres-data:
