version: "3"

x-postgres-creds: &postgres-creds
  POSTGRES_DB: "update-watcher"
  POSTGRES_USER: "update-watcher"
  POSTGRES_PASSWORD: "changeme"
    
x-postgres-url: &postgres-url
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: 5432
  
services:
  postgres:
    image: postgres:15.5
    environment:
      <<: *postgres-creds
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
  migrate:
    image: migrate/migrate:v4.17.0
    entrypoint: 
      - "/entrypoint.sh"
    environment:
      <<:
        - *postgres-creds
        - *postgres-url
    volumes:
      - ../migrations:/migrations
      - ./scripts/entrypoint.sh:/entrypoint.sh
    depends_on:
      - postgres
        
volumes:
  postgres-data:
