# -- cronjob configuration
cronjob:
  # -- crontab configuration defines job schedule 
  # using standard the crontab syntax `* * * * *`
  # cron schedule expressions editor https://crontab.guru/
  crontab: "* * * * * *"
  # -- enables usage of optional 6th field in crontab
  # if set to true syntax `* * * * * *` is allowed
  withSeconds: true


watchers:
  # -- grafanadasboards watcher configuration
  grafanadasboards:
    # -- enable watcher
    # default value is false
    enabled: true
    # -- override watcher name
    # default value grafanadasboards
    name: grafanadashboards
    # -- specify dashboards ids to watch for updates
    # name:  dashboard name to display
    # id:    dashboard id to watch for updates
    dashboards:
      - name: node-exporter-full
        id: 1860
      - name: prometheus-2-0-overview
        id: 3662

  # -- dockerregistry watcher configuration
  dockerregistry:
    # -- enable watcher
    # default value is false
    enabled: true
    # -- override watcher name
    # default value dockerregistry
    name: dockerregistry
    # -- specify images to watch for updates
    # name:       image name to watch for update
    # allowTags:  image tags regexp that are allowed
    # default value is ".+" that match everything
    images:
      - name: vitess/lite
        allowTags: .+
      - name: grafana/grafana
        allowTags: 10\.0\.\d+
        

postgresql:
  # -- postgresql database name
  # should match with POSTGRES_DB in docker-compose.dev.yaml
  database: update-watcher
  # -- postgresql user
  # should match with POSTGRES_USER in docker-compose.dev.yaml
  user: update-watcher
  # -- postgresql password
  # should match with POSTGRES_PASSWORD in docker-compose.dev.yaml
  password: changeme
  # -- postgresql host
  host: 0.0.0.0
  # -- postgresql port
  port: 5432
  
    
webhooks:
  # -- discord webhook configuration
  discord:
    # -- enable webhook
    # default value is false
    enabled: true
    # -- override webhook name
    # default value is discord
    name: discord
    # -- secret webhook url
    url: "<webhook url>"
    # -- embed message avatar url
    avatar: "<image url>"
    # -- embed message author
    author: update-watcher
    # -- embed message color, you have to use Decimal numeral system
    color: 242424
    
  # -- slack webhook configuration
  # TODO: implement this webhook
  slack: 
    # -- enable webhook
    # default value is false
    enabled: false
    # -- override webhook name
    # default value is slack
    name: slack