# -- cronjob configuration
cronjob:
  # -- crontab configuration defines job schedule 
  # using standard the crontab syntax `* * * * *`
  # cron schedule expressions editor https://crontab.guru/
  # optional, default values is "0 */12 * * *"
  crontab: "0 */12 * * *"
  # -- enables usage of optional 6th field in crontab
  # if set to true syntax `* * * * * *` is allowed
  # optional, default values is false
  withSeconds: false
  # -- execute job immediate
  # optional, default value is false
  execImmediate: true


watchers:
  # -- grafanadasboards watcher configuration
  grafanadasboards:
    # -- enable watcher
    # optional, default values is false
    enabled: true
    # -- override watcher name
    # optional, default values is "grafanadasboards"
    name: grafanadashboards
    # -- specify dashboards ids to watch for updates
    # name:  dashboard name to display
    # id:    dashboard id to watch for updates
    dashboards:
      - name: node-exporter-full
        id: 1860
      - name: prometheus-2-0-overview
        id: 3662
    # -- webhook embed message settings
    embed: 
      # -- embed message avatar url
      # optional, default value is "https://cdn.icon-icons.com/icons2/2699/PNG/512/grafana_logo_icon_171048.png"
      avatar: "https://cdn.icon-icons.com/icons2/2699/PNG/512/grafana_logo_icon_171048.png"
      # -- embed message color, you have to use Decimal numeral system
      # optional, default value is 16296468
      color: 16296468
      # -- embed message text that displays above versions list
      # optional, default value is "New revesions released! Checkout:"
      text: "New revesions released! Checkout:"

  # -- dockerregistry watcher configuration
  dockerregistry:
    # -- enable watcher
    # optional, default values is false
    enabled: true
    # -- override watcher name
    # optional, default values is "dockerregistry"
    name: dockerregistry
    # -- specify images to watch for updates
    # name:       image name to watch for update
    # allowTags:  image tags regexp that are allowed
    #             optional, default value is ".+"
    images:
      - name: vitess/lite
        allowTags: .+
      - name: grafana/grafana
        allowTags: 10\.0\.\d+
    # -- webhook embed message settings
    embed: 
      # -- embed message avatar url
      # optional, default value is "https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/97_Docker_logo_logos-512.png"
      avatar: "https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/97_Docker_logo_logos-512.png"
      # -- embed message color, you have to use Decimal numeral system
      # optional, default value is 242424
      color: 242424
      # -- embed message text that displays above versions list
      # optional, default value is "New tags released! Checkout:"
      text: "New tags released! Checkout:"
        

postgresql:
  # -- postgresql database name
  # should match with POSTGRES_DB in docker-compose.dev.yaml
  database: update-watcher
  # -- postgresql user
  # should match with POSTGRES_USER in docker-compose.dev.yaml
  user: update-watcher
  # -- postgresql password
  # should match with POSTGRES_PASSWORD in docker-compose.dev.yaml
  password: changeme
  # -- postgresql host
  # for docker-compose.dev.yaml
  # host: 0.0.0.0
  # for docker-compose.yaml
  host: postgresql
  # -- postgresql port
  port: 5432
  
    
webhooks:
  # -- discord webhook configuration
  discord:
    # -- enable webhook
    # optional, default value is false
    enabled: true
    # -- override webhook name
    # optional, default value is "discord"
    name: discord
    # -- secret webhook url
    url: "<webhook url>"
    

# -- logger configuration
logger:
  # -- log level setting
  # values "DEBUG", "INFO", "WARN", "ERROR"
  # optional, default value in "INFO"
  logLevel: INFO