# -- configuration for production mode
# postgres and discord webhook configuration
# specified in deploy/docker-compose.yaml services.update-watcher.environment

cronjob:
  execImmediate: true


watchers:
  grafanadasboards:
    enabled: true
    dashboards:
      - name: node-exporter-full
        id: 1860
      - name: prometheus-2-0-overview
        id: 3662

  dockerregistry:
    enabled: true
    images:
      - name: vitess/lite
        allowTags: .+
      - name: grafana/grafana
        allowTags: 10\.0\.\d+
        